// flow-typed signature: cf1a13a03749fd0a31a1c73330ce2e6d
// flow-typed version: <<STUB>>/extend_v3.0.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'extend/index' {
  declare module.exports: $Exports<'extend'>;
}
declare module 'extend/index.js' {
  declare module.exports: $Exports<'extend'>;
}
