// flow-typed signature: 2b657d1e19c77d1b1fcebfae247e2d33
// flow-typed version: <<STUB>>/o-tools_v0.10.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'o-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'o-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'o-tools/dist/publish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'o-tools/dist/publish.js' {
  declare module.exports: $Exports<'o-tools/dist/publish'>;
}
