// flow-typed signature: 5ae2b9057eac50a0b107b40cbe3bb150
// flow-typed version: <<STUB>>/port-reservation_v0.3.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'port-reservation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'port-reservation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'port-reservation/dist/port-reservation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'port-reservation/dist/port-reservation.js' {
  declare module.exports: $Exports<'port-reservation/dist/port-reservation'>;
}
