// flow-typed signature: 5e1be6867ba4e2d6b00806e5b40e616b
// flow-typed version: <<STUB>>/standard-markdown_v4.0.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard-markdown/cli' {
  declare module.exports: any;
}

declare module 'standard-markdown/lib/codeBlockUtils' {
  declare module.exports: any;
}

declare module 'standard-markdown/lib/formatter' {
  declare module.exports: any;
}

declare module 'standard-markdown/lib/linter' {
  declare module.exports: any;
}

declare module 'standard-markdown/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard-markdown/cli.js' {
  declare module.exports: $Exports<'standard-markdown/cli'>;
}
declare module 'standard-markdown/index' {
  declare module.exports: $Exports<'standard-markdown'>;
}
declare module 'standard-markdown/index.js' {
  declare module.exports: $Exports<'standard-markdown'>;
}
declare module 'standard-markdown/lib/codeBlockUtils.js' {
  declare module.exports: $Exports<'standard-markdown/lib/codeBlockUtils'>;
}
declare module 'standard-markdown/lib/formatter.js' {
  declare module.exports: $Exports<'standard-markdown/lib/formatter'>;
}
declare module 'standard-markdown/lib/linter.js' {
  declare module.exports: $Exports<'standard-markdown/lib/linter'>;
}
declare module 'standard-markdown/tests/index.js' {
  declare module.exports: $Exports<'standard-markdown/tests/index'>;
}
