// flow-typed signature: 8faac8498bdc02ff4a758e2b701bb18f
// flow-typed version: <<STUB>>/string-argv_v0.0.2/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-argv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-argv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'string-argv/index' {
  declare module.exports: $Exports<'string-argv'>;
}
declare module 'string-argv/index.js' {
  declare module.exports: $Exports<'string-argv'>;
}
