// flow-typed signature: 5118c09bfd98405fc86f56b904bc3588
// flow-typed version: <<STUB>>/text-stream-search_v2.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-stream-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-stream-search' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text-stream-search/dist/searchers/base-search' {
  declare module.exports: any;
}

declare module 'text-stream-search/dist/searchers/regex-search' {
  declare module.exports: any;
}

declare module 'text-stream-search/dist/searchers/string-search' {
  declare module.exports: any;
}

declare module 'text-stream-search/dist/text-stream-search' {
  declare module.exports: any;
}

declare module 'text-stream-search/dist/typedefs/reject-function' {
  declare module.exports: any;
}

declare module 'text-stream-search/dist/typedefs/resolve-function' {
  declare module.exports: any;
}

declare module 'text-stream-search/dist/typedefs/search' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text-stream-search/dist/searchers/base-search.js' {
  declare module.exports: $Exports<'text-stream-search/dist/searchers/base-search'>;
}
declare module 'text-stream-search/dist/searchers/regex-search.js' {
  declare module.exports: $Exports<'text-stream-search/dist/searchers/regex-search'>;
}
declare module 'text-stream-search/dist/searchers/string-search.js' {
  declare module.exports: $Exports<'text-stream-search/dist/searchers/string-search'>;
}
declare module 'text-stream-search/dist/text-stream-search.js' {
  declare module.exports: $Exports<'text-stream-search/dist/text-stream-search'>;
}
declare module 'text-stream-search/dist/typedefs/reject-function.js' {
  declare module.exports: $Exports<'text-stream-search/dist/typedefs/reject-function'>;
}
declare module 'text-stream-search/dist/typedefs/resolve-function.js' {
  declare module.exports: $Exports<'text-stream-search/dist/typedefs/resolve-function'>;
}
declare module 'text-stream-search/dist/typedefs/search.js' {
  declare module.exports: $Exports<'text-stream-search/dist/typedefs/search'>;
}
