export { FinishedProcess, instanceOfFinishedProcess } from "./finished-process"
export { KilledProcess, instanceOfKilledProcess } from "./killed-process"
export { RunningProcess } from "./running-process"
export * as scanner from "./scanner"
export { start, StartOptions } from "./start"
